### ISSUE TITLE
Page Example

### ISSUE THREAD

**Issue by magnokf** [vitormicillo/filament-map-picker#1]
Could you please add a demo image at ReadMe?

Thxs

**Comment by vitormicillo** [comment]
I am still developing this plugin, I am having some issues to show the drawings tools
but so far I have the map tiles rendering with no issues any more.
![image](https://github.com/user-attachments/assets/6d7330f1-c418-42ff-8af6-bc84c24ed06f)

**Comment by vitormicillo** [comment]
> Could you please add a demo image at ReadMe?
> 
> Thxs

Update your composer now, at least the drawing tools is visible in the map with the latest update
